name: CI Pipeline
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}
      - name: Build Docker image
        run: docker build -t my-flask-app .
      - name: Test Docker image
        run: echo "Test"
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/my-flask-app:latest
        if: github.ref == 'refs/heads/main'